liip_imagine:
    driver: "gd"
    twig:
        mode: lazy
    webp:
        generate: true
    filter_sets:
        imageproduit:
            quality: 75
            filters:
                thumbnail:
                    size: [ 120, 90 ]
                    mode: outbound